defaults:
  - data_loader

features:
  include_past_days: 30
  preprocessing_data_path: data/preprocessing/${data_loader.TICKER}_processed_data.csv
  TEMPORAL_SCALER_PATH: models/temporalScaler.pkl
  STATIC_SCALER_PATH: models/staticScaler.pkl
